name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Boost
      run: sudo apt-get update && sudo apt-get install -y libboost-all-dev
    - uses: actions/checkout@v4
    - name: Configure and Build
      run: |
        cmake -B ${{github.workspace}}
        cmake --build ${{github.workspace}}
    - name: Create build_version.json
      run: |
        echo '{
          "version": "1.0.${{ github.run_number }}",
          "commit": "${{ github.sha }}",
          "build_time": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        }' > ./build_version.json
        git config --global user.name "caolandix"
        git config --global user.email "co.domhnaill@aeshna.net"
        git add ./build_version.json 
        git commit -m "Automated build: update DarkSynthesis code"
        git push

